systemProp.version = 4.0.0

# TLS ?? - ???? TLSv1.2
systemProp.jdk.tls.client.protocols=TLSv1.2
systemProp.javax.net.ssl.trustStoreType=JKS

# ??????????
org.gradle.internal.http.connectionTimeout=120000
org.gradle.internal.http.socketTimeout=120000

# JVM ??
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# ??????
org.gradle.parallel=true
org.gradle.caching=true